_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  d10test_facets_pretty_paths: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  facets: 0
  facets_pretty_paths: 0
  facets_range_widget: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  jquery_ui: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  media: 0
  media_library: 0
  memcache: 0
  memcache_admin: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  path_alias_xt: 0
  responsive_image: 0
  rest: 0
  search_api: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  svg_image_field: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_data_export: 0
  views_ui: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  bootstrap5: 0
  d10test_theme: 0
profile: standard
