_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 72f7608c-b2c1-48f4-bf9a-1cc83379840a
name: D10Test
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /catalog
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
